#!/usr/bin/env ruby

# Loads in lib dir to use classes defined there
$LOAD_PATH.unshift( File.join( File.dirname(__FILE__), 'lib' ) )

# load custom classes
require 'csv_parser'
require 'data_normalizer'

# TODO: create options parser that will explain how this script will work
def main()

  # initialize class variables
  csv_parser = CSVParser.new()
  data_normalizer = DataNormalizer.new()

  parsed_csv = csv_parser.parse_input()
  output = data_normalizer.normalize_data(parsed_csv)

  puts csv_parser.create_stdout_csv(parsed_csv.headers, output)
end

main
